spring:
  datasource:
#    url: jdbc:mariadb://localhost:3306/school
    url: jdbc:h2:tcp://localhost/~/board
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create